# ./config/keywords.yaml
keywords:
  - Medical Waste
  - Incineration
  - Incinerator
  - Volume Reduction
  - Safe Disposal
  - Waste Treatment
  - Waste Incineration
  - Hazardous Waste
  - Pyrolysis Incineration
  - High-Temperature Incineration
  - Plasma Incineration
  - Rotary Furnace
  - Fixed Furnace
  - Vertical Furnace
  - Horizontal Furnace
